name: publish

on:
    # push:
    #     branches:
    #         - "**"
    #     tags:
    #         - "v*"
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - run: ls
            - run: npm install -f
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: ls ./node_modules/@img
            - run: npx vsce --version
            - run: cat package.json
            - shell: pwsh
              run: npm run package-full

            - shell: pwsh
              run: npm run publish-extension
            # - uses: actions/upload-artifact@v2
            #   with:
            #       name: ${{ env.target }}
            #       path: "*.vsix"

    # publish:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     # if: success() && startsWith( github.ref, 'refs/tags/')
    #     steps:
    #         - uses: actions/download-artifact@v2
    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: 18.x
    #         - name: Install the vsce npm package
    #           run: npm install -g vsce

    #         - run: vsce publish -p ${{ secrets.VSCE_PAT }} --packagePath $(find . -iname *.vsix)
    #           env:
    #               VSCE_PAT: ${{ secrets.VSCE_PAT }}
