name: publish

on:
    # push:
    #     branches:
    #         - "**"
    #     tags:
    #         - "v*"
    workflow_dispatch:
        inputs:
            publish:
                type: boolean
                description: Publish extension
                default: true
            pre-release:
                type: boolean
                description: Publish for devs
                default: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - run: npm install -f
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - run: npm i -O @img/sharp-darwin-arm64 @img/sharp-darwin-x64 @img/sharp-libvips-darwin-arm64 @img/sharp-libvips-darwin-x64 @img/sharp-win32-x64
            - run: npm list
            - run: ls ./node_modules/@img
            - run: npx vsce --version

            - run: npm run package-full
              env:
                  PRE_RELEASE: ${{ github.event.inputs.pre-release}}
            - run: ls
            - run: ls ./vsix-packages
            - run: cat ./package.json
            - if: ${{ github.event.inputs.publish }}
              run: npx vsce publish -p ${{ secrets.VSCE_PAT }} ${{ github.event.inputs.pre-release == true && '--pre-release' || ''}} --packagePath $(find ./vsix-packages -iname *.vsix)
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
            - uses: actions/upload-artifact@v2
              with:
                  name: "packs"
                  path: "./vsix-packages"

    # publish:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     # if: success() && startsWith( github.ref, 'refs/tags/')
    #     steps:
    #         - uses: actions/download-artifact@v2
    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: 18.x
    #         - name: Install the vsce npm package
    #           run: npm install -g vsce

    #         - run: vsce publish -p ${{ secrets.VSCE_PAT }} --packagePath $(find . -iname *.vsix)
    #           env:
    #               VSCE_PAT: ${{ secrets.VSCE_PAT }}
