name: test-vars

on:
    workflow_dispatch:

jobs:
    test-vars:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ secrets.VSCE_PAT }}"
            - run: echo "${{ secrets.GITHUB_TOKEN }}"
